window.WC_TOURNAMENT = window.WC_TOURNAMENT || {
  groups: {
    A: ["Mexico", "South Africa", "South Korea", "Czech Republic"],
    B: ["Canada", "Bosnia and Herzegovina", "Qatar", "Switzerland"],
    C: ["Brazil", "Morocco", "Haiti", "Scotland"],
    D: ["United States", "Paraguay", "Australia", "Turkey"],
    E: ["Germany", "Curaçao", "Ivory Coast", "Ecuador"],
    F: ["Netherlands", "Japan", "Sweden", "Tunisia"],
    G: ["Belgium", "Egypt", "Iran", "New Zealand"],
    H: ["Spain", "Cape Verde", "Saudi Arabia", "Uruguay"],
    I: ["France", "Senegal", "Iraq", "Norway"],
    J: ["Argentina", "Algeria", "Austria", "Jordan"],
    K: ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    L: ["England", "Croatia", "Ghana", "Panama"],
  },
};

window.WC_TEAM_META = window.WC_TEAM_META || {
  algeria: { team: "Algeria", code: "ALG", flag: "assets/flags/dz.png" },
  argentina: { team: "Argentina", code: "ARG", flag: "assets/flags/ar.png" },
  australia: { team: "Australia", code: "AUS", flag: "assets/flags/au.png" },
  austria: { team: "Austria", code: "AUT", flag: "assets/flags/at.png" },
  belgium: { team: "Belgium", code: "BEL", flag: "assets/flags/be.png" },
  bosnia_and_herzegovina: { team: "Bosnia and Herzegovina", code: "BIH", flag: "assets/flags/ba.png" },
  brazil: { team: "Brazil", code: "BRA", flag: "assets/flags/br.png" },
  canada: { team: "Canada", code: "CAN", flag: "assets/flags/ca.png" },
  cape_verde: { team: "Cape Verde", code: "CPV", flag: "assets/flags/cv.png" },
  colombia: { team: "Colombia", code: "COL", flag: "assets/flags/co.png" },
  croatia: { team: "Croatia", code: "CRO", flag: "assets/flags/hr.png" },
  cura_ao: { team: "Curaçao", code: "CUW", flag: "assets/flags/cw.png" },
  czech_republic: { team: "Czech Republic", code: "CZE", flag: "assets/flags/cz.png" },
  dr_congo: { team: "DR Congo", code: "COD", flag: "assets/flags/cd.png" },
  ecuador: { team: "Ecuador", code: "ECU", flag: "assets/flags/ec.png" },
  egypt: { team: "Egypt", code: "EGY", flag: "assets/flags/eg.png" },
  england: { team: "England", code: "ENG", flag: "assets/flags/gb-eng.png" },
  france: { team: "France", code: "FRA", flag: "assets/flags/fr.png" },
  germany: { team: "Germany", code: "GER", flag: "assets/flags/de.png" },
  ghana: { team: "Ghana", code: "GHA", flag: "assets/flags/gh.png" },
  haiti: { team: "Haiti", code: "HAI", flag: "assets/flags/ht.png" },
  iran: { team: "Iran", code: "IRN", flag: "assets/flags/ir.png" },
  iraq: { team: "Iraq", code: "IRQ", flag: "assets/flags/iq.png" },
  ivory_coast: { team: "Ivory Coast", code: "CIV", flag: "assets/flags/ci.png" },
  japan: { team: "Japan", code: "JPN", flag: "assets/flags/jp.png" },
  jordan: { team: "Jordan", code: "JOR", flag: "assets/flags/jo.png" },
  mexico: { team: "Mexico", code: "MEX", flag: "assets/flags/mx.png" },
  morocco: { team: "Morocco", code: "MAR", flag: "assets/flags/ma.png" },
  netherlands: { team: "Netherlands", code: "NED", flag: "assets/flags/nl.png" },
  new_zealand: { team: "New Zealand", code: "NZL", flag: "assets/flags/nz.png" },
  norway: { team: "Norway", code: "NOR", flag: "assets/flags/no.png" },
  panama: { team: "Panama", code: "PAN", flag: "assets/flags/pa.png" },
  paraguay: { team: "Paraguay", code: "PAR", flag: "assets/flags/py.png" },
  portugal: { team: "Portugal", code: "POR", flag: "assets/flags/pt.png" },
  qatar: { team: "Qatar", code: "QAT", flag: "assets/flags/qa.png" },
  saudi_arabia: { team: "Saudi Arabia", code: "KSA", flag: "assets/flags/sa.png" },
  scotland: { team: "Scotland", code: "SCO", flag: "assets/flags/gb-sct.png" },
  senegal: { team: "Senegal", code: "SEN", flag: "assets/flags/sn.png" },
  south_africa: { team: "South Africa", code: "RSA", flag: "assets/flags/za.png" },
  south_korea: { team: "South Korea", code: "KOR", flag: "assets/flags/kr.png" },
  spain: { team: "Spain", code: "ESP", flag: "assets/flags/es.png" },
  sweden: { team: "Sweden", code: "SWE", flag: "assets/flags/se.png" },
  switzerland: { team: "Switzerland", code: "SUI", flag: "assets/flags/ch.png" },
  tunisia: { team: "Tunisia", code: "TUN", flag: "assets/flags/tn.png" },
  turkey: { team: "Turkey", code: "TUR", flag: "assets/flags/tr.png" },
  united_states: { team: "United States", code: "USA", flag: "assets/flags/us.png" },
  uruguay: { team: "Uruguay", code: "URU", flag: "assets/flags/uy.png" },
  uzbekistan: { team: "Uzbekistan", code: "UZB", flag: "assets/flags/uz.png" },
};

/*
  Team names used in WC_TOURNAMENT.groups must match the "team" values above
  (or their lowercase/underscore key) so the frontend can resolve flags.
*/
